version: '3.7'
services:
  web:
    image: ghcr.io/open-webui/open-webui:v0.6.41@sha256:3e07bcede92e97cc3e741de095045a8b5d20bc257ecdb713bd2a47f68e9dff72
    volumes:
    - ${APP_DATA_DIR}/data/open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: $APP_OLLAMA_URL
    restart: on-failure
