version: '3.7'
services:
  server:
    image: ghcr.io/hotio/qbittorrent:release-5.1.2@sha256:4c731e88dd419a20f0e158cef9672e902a7e2c71acea48b8989567f00b5fb095
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${UMBREL_ROOT}/data/storage/downloads:/app/qBittorrent/downloads
    restart: on-failure
