version: '3.7'
services:
  server:
    image: privatebin/nginx-fpm-alpine:2.0.3@sha256:f8fcca3d71dfe983c8404dc6dbcc140ab12cebe8d4ee62329254c79b5934b1e8
    user: 1000:1000
    read_only: true
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/privatebin-data:/srv/data
