version: '3.7'
services:
  web:
    image: ckulka/baikal:0.10.1@sha256:2385faeb7cc165d2b080c0ed8c84cc59e84d03107f814ad897ab62684c792f7b
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/config:/var/www/baikal/config
    - ${APP_DATA_DIR}/data/Specific:/var/www/baikal/Specific
