version: '3.7'
services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest@sha256:abd691b4293b020a317de8794737671e0315159efcb868e8a4124d6f0611f7ae
    restart: on-failure
    volumes:
    - linkstack_data:/htdocs
volumes:
  linkstack_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${APP_DATA_DIR}/data
