version: '3.7'
services:
  server:
    image: sbs20/scanservjs:v3.0.4@sha256:e42263444a8dd5d533ead7d9eb2ef5fd9ca7a4a80569a6f9c14b7a3c21b9c7ca
    restart: on-failure
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/scans:/var/lib/scanservjs/output
    - ${APP_DATA_DIR}/data/config:/etc/scanservjs
    - /var/run/dbus:/var/run/dbus
    - /dev:/dev
    privileged: true
