version: '3.7'
services:
  server:
    image: linuxserver/emby:version-4.9.1.90@sha256:8a0a5ae9844c83380fa72c9964c0212f5d1488ea61ecc0adac64a5ab49c83cb1
    environment:
      TZ: Europe/Berlin
      UID: 1000
      GID: 1000
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/config:/config:rw
    - ${UMBREL_ROOT}/data/storage/downloads:/downloads
