version: '3.7'
services:
  app:
    image: ghcr.io/sheshbabu/zen/zen:1.5.0@sha256:370d7ae0d8b4d06593b44ffa1cfde5d15c7f80abe4bbe8d94e86d8d29e250270
    user: 1000:1000
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/app:/data
    - ${APP_DATA_DIR}/data/images:/images
