version: '3.7'
services:
  web:
    image: ghcr.io/richardr1126/openreader-webui:1.1.1@sha256:cd647d6f3a039a5a74d381f9c1b432a0adf53d0bbd0a1d4c61e1bd92523b6892
    user: 1000:1000
    environment:
    - API_BASE=http://kokoro_web_1:8880/v1
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/docstore:/app/docstore
