version: '3.7'
services:
  server:
    image: ghcr.io/lissy93/web-check:1.0.0@sha256:5c310ff7d81cd87cf69a2738f930da2e5050aada543012720a859f01e4c5654c
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data:/app/data
