services:
  server:
    build: .
    shm_size: '1gb'
    mem_limit: 3072m
    oom_score_adj: 500
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=
      - PASSWORD=
      - PROXY_URL=
      - TZ=Europe/Istanbul
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
