version: '3.7'

services:
  server:
    build: .
    shm_size: '1gb'
    mem_limit: 1536m
    oom_score_adj: 500
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=
      - PASSWORD=
      - CHROME_CLI=--remote-debugging-port=9222 --remote-allow-origins=* --restore-last-session --disable-blink-features=AutomationControlled --disable-infobars --disable-dev-shm-usage
      - TZ=Europe/Istanbul
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
