version: '3.7'
services:
  ollama:
    image: ollama/ollama:0.12.10@sha256:e8c3d1f6ad16323bc40dc63eff0701d4fc32113f75a86b54b3e836eef8290de6
    environment:
      OLLAMA_ORIGINS: '*'
      OLLAMA_CONTEXT_LENGTH: 8192
    volumes:
    - ${APP_DATA_DIR}/data:/root/.ollama
    restart: on-failure
