version: '3.7'
services:
  web:
    privileged: true
    restart: on-failure
    image: ghcr.io/blakeblackshear/frigate:0.16.3@sha256:cf4305d9f1c673d71c4d0fab30ca56ca05ac91168711a74ee7867a4691a7ad02
    shm_size: 128mb
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/storage:/media/frigate
    ports:
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${APP_PASSWORD}
