version: '3.7'
services:
  app:
    image: stirlingtools/stirling-pdf:2.1.3@sha256:6ec3e0d5d92977c58c40ce5ab78a6237b1e9a86e80b28792b4ff76db1d3fdf90
    restart: on-failure
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/tessdata:/usr/share/tessdata
    - ${APP_DATA_DIR}/data/configs:/configs
    - ${APP_DATA_DIR}/data/logs:/logs
    - ${APP_DATA_DIR}/data/pipeline:/pipeline
    environment:
      DOCKER_ENABLE_SECURITY: 'false'
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: 'true'
      LANGS: ALL
      SECURITY_ENABLELOGIN: 'false'
