version: '3.7'
services:
  main:
    image: libretranslate/libretranslate:v1.6.5@sha256:a3518195e4e810ba0d9dd251a851f24918059d757ef3c5cf8e0f881daf4242fc
    restart: on-failure
    tty: true
    healthcheck:
      test:
      - CMD-SHELL
      - ./venv/bin/python scripts/healthcheck.py
    environment:
    - LT_API_KEYS=true
    - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
    - LT_UPDATE_MODELS=true
    volumes:
    - ${APP_DATA_DIR}/data/api_keys:/app/db
    - ${APP_DATA_DIR}/data/models:/home/libretranslate/.local:rw
