manifestVersion: 1
id: esphome
category: automation
name: ESPHome
version: 2025.11.5
tagline: Intelligently manage all your ESP8266/ESP32 devices
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
developer: ESPHome
website: https://esphome.io
dependencies: []
repo: https://github.com/esphome/esphome
support: https://community.home-assistant.io/c/esphome
port: 6052
path: ''
defaultUsername: ''
defaultPassword: ''
torOnly: false
releaseNotes: "This release includes important bug fixes and stability improvements:\n  - Fixed binary sensor reporting of 'unknown' states\n  - LVGL number inputs now correctly save values on interactive changes\n  - Addressed a scheduler issue related to missing locks during defer queue processing\n  - Resolved WiFi scan timeout loops that occurred when no networks were found or scans failed\n  - Corrected a case sensitivity error in the MQTT logger method\n\n\nFull release notes can be found at https://esphome.io/changelog/2025.11.5.html"
