version: '3.7'
services:
  app:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.1.0@sha256:be68b700d56e9454a9b92902a3fcd25adebfef93e3cd24179374303fc2e9f14c
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
    - ${APP_BITCOIN_P2P_PORT}:${APP_BITCOIN_P2P_PORT}
    - ${APP_BITCOIN_RPC_PORT}:${APP_BITCOIN_RPC_PORT}
    volumes:
    - ${APP_DATA_DIR}/data:/data
    environment:
      BITCOIND_EXTRA_ARGS: -deprecatedrpc=create_bdb
      APPS_SUBNET: ${NETWORK_IP}/16
      P2P_PORT: ${APP_BITCOIN_P2P_PORT}
      P2P_WHITEBIND_PORT: ${APP_BITCOIN_P2P_WHITEBIND_PORT}
      RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      TOR_PORT: ${APP_BITCOIN_TOR_PORT}
      ZMQ_RAWBLOCK_PORT: ${APP_BITCOIN_ZMQ_RAWBLOCK_PORT}
      ZMQ_RAWTX_PORT: ${APP_BITCOIN_ZMQ_RAWTX_PORT}
      ZMQ_HASHBLOCK_PORT: ${APP_BITCOIN_ZMQ_HASHBLOCK_PORT}
      ZMQ_SEQUENCE_PORT: ${APP_BITCOIN_ZMQ_SEQUENCE_PORT}
      ZMQ_HASHTX_PORT: ${APP_BITCOIN_ZMQ_HASHTX_PORT}
      TOR_HOST: ${APP_BITCOIN_TOR_PROXY_IP}
      TOR_SOCKS_PORT: '9050'
      TOR_CONTROL_PORT: '9051'
      TOR_CONTROL_PASSWORD: moneyprintergobrrr
      I2P_HOST: ${APP_BITCOIN_I2P_DAEMON_IP}
      I2P_SAM_PORT: '7656'
      BITCOIND_IP: ${APP_BITCOIN_NODE_IP}
      RPC_USER: ${APP_BITCOIN_RPC_USER}
      RPC_PASS: ${APP_BITCOIN_RPC_PASS}
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      P2P_HIDDEN_SERVICE: ${APP_BITCOIN_P2P_HIDDEN_SERVICE}
      RPC_HIDDEN_SERVICE: ${APP_BITCOIN_RPC_HIDDEN_SERVICE}
    networks:
      default:
        ipv4_address: $APP_BITCOIN_NODE_IP
  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: 1000:1000
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
    - ${TOR_DATA_DIR}:/data
    environment:
      HOME: /tmp
    networks:
      default:
        ipv4_address: ${APP_BITCOIN_TOR_PROXY_IP}
  i2pd_daemon:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    user: root
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/i2pd:/home/i2pd/data
    networks:
      default:
        ipv4_address: ${APP_BITCOIN_I2P_DAEMON_IP}
