version: '3.7'
services:
  server:
    image: fallenbagel/jellyseerr:2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
    volumes:
    - ${APP_DATA_DIR}/data/config:/app/config
    restart: on-failure
